import { Analytics } from '@vercel/analytics/react';
import { Inter } from 'next/font/google'
import { ToastContainer } from 'react-toastify';
import { cookies } from "next/headers";

import Provider from './provider'

import './globals.css'
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "SiteGuardian",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

type IProps = {
  children: React.ReactNode;
}
export default function (props: IProps) {
  return (
    <html lang="en" className='dark bg-background overscroll-none'>
      <body className={`font-sans ${inter.variable}`}>
        <Provider cookies={cookies()}>
          <main className='bg-gray-950 w-screen h-screen'>
            {props.children}
          </main>
          <Analytics />
        </Provider>
        <ToastContainer
          position="top-right"
          autoClose={3_000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick={true}
          rtl={false}
          pauseOnFocusLoss={true}
          draggable={true}
          pauseOnHover={true}
          theme="dark"
        />
      </body>
    </html>
  );
}
